spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring_security_example
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    properties:
      hibernate:
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false

flyway:
  enabled: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 20000